WIP

diff --git a/script/build-macos b/script/build-macos
--- a/script/build-macos
+++ b/script/build-macos
@@ -1,15 +1,44 @@
 #!/bin/bash
 ### usage: build-macos [opts..]
 ###
-### Builds "Tangara Companion.app" for macOS
+### Cross compiles the macOS distribution from a Linux host
 
 set -euo pipefail
 cd "$(dirname "$0")/.."
 source script/lib/functions.sh
 source script/lib/error.sh
 
-BUILD=release
+# configure me!
+PROFILE=release
 TARGET=x86_64-apple-darwin
+ARCH=x86_64
+
+# check for MACOS_KITS
+[ -n "${MACOS_KITS:-}" ] || die "MACOS_KITS not set, cannot proceed. Hailey will document this whole thing eventually"
+[ -d "$MACOS_KITS/osxcross/bin" ] || die "$MACOS_KITS/osxcross/bin does not exist, cannot proceed"
+
+# grab version number from git
+version="$(git describe --tags)"
+info "Building version $version"
+
+# put cross compiler into PATH
+export PATH="$MACOS_KITS/osxcross/bin:$PATH"
+
+# set cross compile vars
+export PKG_CONFIG_PATH="$MACOS_KITS/gtk/lib/pkgconfig"
+export PKG_CONFIG_ALLOW_CROSS=1
+export CC=x86_64-apple-darwin23-clang
+export CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER="$CC"
+
+# pass --release to cargo if PROFILE==release:
+cargo_args=()
+[[ "$PROFILE" == "release" ]] && cargo_args+="--release"
+
+# do the build
+log-command cargo build --target="$TARGET" "${cargo_args[@]}"
+
+# this is the end of the new cross compiler bizzo
+exit 1
 
 add-pkgconfig-path() {
     local path="$1"
@@ -41,16 +70,8 @@ use-brew-pkg gtk4
 use-brew-pkg libadwaita
 use-brew-pkg curl
 
-# grab version number from git
-version="$(git describe --tags)"
-info "Version $version"
 
-# pass --release to cargo if BUILD==release:
-cargo_args=()
-[[ "$BUILD" == "release" ]] && cargo_args+="--release"
 
-# do the build
-log-command cargo build --target="$TARGET" "${cargo_args[@]}"
 
 # assemble macOS .app bundle
 info "assembling 'Tangara Companion.app' bundle"
